[package]
name = "kds_tagore-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kds_tagore-rs"
path = "src/main.rs"

[dependencies]
lariv-rs = { version = "0.1.0",
	# path = "../../lariv-rs",
	git = "https://github.com/lariv-in/lariv-rs", rev = "257089056e98e2ded2488d134ea445d54d95d375",
	default-features = false, features = [
		"plugin-users",
		"plugin-dashboard",
		"plugin-filesystem",
		"plugin-website",
		"plugin-crm",
		"plugin-finance",
] }
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1", features = ["backtrace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
chrono = "0.4"
sea-orm = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-sqlite"] }

[profile.release]
lto = "thin"
strip = true
codegen-units = 1
