[package]
name = "kds_tagore-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kds-tagore-rs"
path = "src/main.rs"

[dependencies]
lariv-rs = { version = "0.1.0",
	path = "../../lariv-rs",
	# git = "https://github.com/lariv-in/lariv-rs", rev = "dfb4ed68a857d9c57ffd05995da167e947ed8ef9",
	default-features = false, features = [
		"plugin-users",
		"plugin-dashboard",
		"plugin-filesystem",
		"plugin-website",
		"plugin-crm",
		"plugin-tasks",
		"plugin-finance",
		"plugin-forms",
		"plugin-hr",
		"plugin-llm-assistant",
] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
async-trait = "0.1"
frunk = { version = "0.5.0", features = ["serde", "std"] }
frunk_core = "0.5.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
chrono = { version = "0.4", features = ["serde", "clock"] }
axum = { version = "0.8", features = ["form", "macros"] }
maud = { version = "0.27", features = ["axum"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust_decimal = { version = "1", features = ["serde-with-str", "maths"] }
sea-orm = { version = "2.0", features = [
	"sqlx-postgres",
	"sqlx-sqlite",
	"runtime-tokio-rustls",
	"macros",
	"with-chrono",
	"with-json",
	"with-rust_decimal",
] }
sea-orm-migration = { version = "2.0", features = [
	"sqlx-postgres",
	"sqlx-sqlite",
	"runtime-tokio-rustls",
] }
calamine = "0.36"
rust_xlsxwriter = "0.99"
uuid = { version = "1", features = ["v4"] }
rune = "0.14"
thiserror = "2"
minijinja = { version = "2", features = ["loader"] }
num2words = "1"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
tower = { version = "0.5", features = ["util"] }

[profile.release]
lto = "thin"
strip = true
codegen-units = 1
