[package]
name = "kds-plugin-machinery-schedule"
version = "0.1.0"
edition.workspace = true
description = "KDS Tagore machinery schedule plugin"

[dependencies]
kds-plugin-formula = { workspace = true }
kds-plugin-hr-role = { workspace = true }
lariv-core = { workspace = true }
lariv-plugin-hr = { workspace = true }
lariv-plugin-filesystem = { workspace = true }
lariv-plugin-users = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
maud = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
